steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/buildboard-web:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/buildboard-web:latest', '.']

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/buildboard-web:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/buildboard-web:latest']

  # Deploy to GKE
  # Note: You need to set the _CLUSTER and _ZONE substitutions in your Cloud Build Trigger
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'

  # Update the deployment with the new image
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/buildboard-app', 'buildboard=gcr.io/$PROJECT_ID/buildboard-web:$COMMIT_SHA']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'

images:
  - 'gcr.io/$PROJECT_ID/buildboard-web:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/buildboard-web:latest'

substitutions:
  _ZONE: us-central1-a # Default, change in Trigger settings
  _CLUSTER: buildboard-cluster # Default, change in Trigger settings
